# Generated by Django 5.2.6 on 2025-09-28 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'verbose_name_plural': 'Equipment Categories'},
        ),
    ]
